language: cpp
dist: trusty
sudo: required

compiler:
  - gcc
  - clang

before_install:
# install needed deps
  - sudo apt-get update -qq
  - sudo apt-get install build-essential clang cmake libboost-thread1.61-dev libboost-system1.61-dev libboost-filesystem1.61-dev libboost-date-time1.61-dev libboost-atomic1.61-dev libboost-chrono1.61-dev libogg-dev libvorbis-dev libflac-dev libfaad-dev libncursesw5-dev libasound2-dev libpulse-dev pulseaudio libmicrohttpd-dev libmp3lame-dev libcurl4-openssl-dev

script:
  - mkdir "build"
  - cd build
  - cmake ..
  - make -j 2 
